### ISSUE TITLE
zombie language server

### ISSUE THREAD

**Issue by alanz** [erlang-ls/vscode#11]
Using version 0.0.4, I just had a scenario where the language server kept on running after the vscode instance stopped (ok, maybe I `kill - 15`'d it).

It carried on running, and doing work as the underlying project changed.

Perhaps the server should shut itself down if the connection disappears for longer than some specified timeout time.

**Comment by adam-becker** [comment]
Currently the code makes no attempt to stop the language server as far as I know, I can look into this and see the proper way to handle this. Maybe the language server isn't responding to the kill signal vscode uses.

**Comment by robertoaloi** [comment]
Yes, I noticed the same. Thanks for reporting.

**Comment by alanz** [comment]
This problem still exists for TCP,  I think we should generalise the stdio solution.
