### ISSUE TITLE
Visual Studio Code not interacting with Language Server on MacOS

### ISSUE THREAD

**Issue by rocveralfre** [erlang-ls/vscode#16]
Hello,
Today I was testing the extension on latest MacOS (Catalina 10.15.2) and Erlang version 22.1.2.

After installing the extension I was able to see the language server running in the processes (with ps) {to be honest I saw multiple instances of the language server, but I see there is already another issue regarding this topic}

Every time, the language server was run with connection `transport` type set to `stdio`.

Unfortunately, when browsing the files I was not able to find any language server feature offered by the extension (function applications for example).

I'm located in GMT+1 timezone and can provide whatever information needed in order to use in a production environment.

Thanks for the help

**Comment by alanz** [comment]
FWIW I am on Catalina 10.15.2, with Erlang version 22.2.1 and it works for me.

I get syntax highlight, spec info provided on hover, jump to definition, etc.

**Comment by rocveralfre** [comment]
Could you please upload a short video/picture showing it?

In some hours I will be able to provide more details on my end..

The only thing I'm sure is that the .erl file is recognized as an Erlang File, I will also enable the debug log with the language server and post whatever I'm able to see..

**Comment by alanz** [comment]
<img width="670" alt="Screenshot 2020-01-03 at 13 29 23" src="https://user-images.githubusercontent.com/409607/71725867-45f03e80-2e2d-11ea-9518-b146be17ce56.png">

**Comment by jfacorro** [comment]
@rocveralfre It could be that there's something in the project that `erlang_ls` is not handling correctly and therefore crashing somehow. Is the project you are using in GitHub by any chance?

**Comment by rocveralfre** [comment]
It may be a chance, indeed. Unfortunately, I cannot provide the source code because it's protected by NDA, but I will try to launch the same file as from the screenshot and report back!

**Comment by rocveralfre** [comment]
Current situation:

The language server is running, at least once...

```
veralfre @ ~/github/erlang_ls [17:51] [0] $ ps uax | grep "erlang_ls"
veralfre           935   0,0  0,2  5446968  27680   ??  S     5:47pm   0:00.44 /Users/veralfre/.vscode/extensions/erlang-ls.erlang-ls-0.0.5/erlang_ls/_build/default/bin/erlang_ls -B -- -root /usr/local/lib/erlang -progname erl -- -home /Users/veralfre -- -boot no_dot_erlang -noshell -escript main erlang_ls -pz erlang_ls/erlang_ls/ebin -run escript start -- -extra /Users/veralfre/.vscode/extensions/erlang-ls.erlang-ls-0.0.5/erlang_ls/_build/default/bin/erlang_ls --transport stdio
veralfre          1120   0,0  0,0  4277536    620 s000  R+    5:57pm   0:00.00 grep erlang_ls
veralfre          1113   0,0  0,2  5449604  27960   ??  S     5:56pm   0:00.39 /Users/veralfre/.vscode/extensions/erlang-ls.erlang-ls-0.0.5/erlang_ls/_build/default/bin/erlang_ls -B -- -root /usr/local/lib/erlang -progname erl -- -home /Users/veralfre -- -boot no_dot_erlang -noshell -escript main erlang_ls -pz erlang_ls/erlang_ls/ebin -run escript start -- -extra /Users/veralfre/.vscode/extensions/erlang-ls.erlang-ls-0.0.5/erlang_ls/_build/default/bin/erlang_ls --transport stdio
veralfre          1060   0,0  0,2  5425028  27684   ??  S     5:50pm   0:00.41 /Users/veralfre/.vscode/extensions/erlang-ls.erlang-ls-0.0.5/erlang_ls/_build/default/bin/erlang_ls -B -- -root /usr/local/lib/erlang -progname erl -- -home /Users/veralfre -- -boot no_dot_erlang -noshell -escript main erlang_ls -pz erlang_ls/erlang_ls/ebin -run escript start -- -extra /Users/veralfre/.vscode/extensions/erlang-ls.erlang-ls-0.0.5/erlang_ls/_build/default/bin/erlang_ls --transport stdio
```
The plugin is installed:

![Schermata 2020-01-03 alle 17 58 54](https://user-images.githubusercontent.com/39377051/71736985-c07f8500-2e52-11ea-91f0-ebe31ce9256d.png)

I'm running Erlang/OTP 22 [erts-10.6.1], however even when hovering on the very sample file as the screenshot I get no prompt...

![Schermata 2020-01-03 alle 18 02 20](https://user-images.githubusercontent.com/39377051/71737163-3a177300-2e53-11ea-98dc-92ed1205a783.png)

If you need further information, I'd glad to help you!

**Comment by robertoaloi** [comment]
@rocveralfre Sorry about the late reply. Could you please try the latest version of the extension (0.0.7 or superior) and verify this is still an issue? If it is, could you please send us the server side logs that are in `/Users/veralfre/Library/Logs/erlang_ls/`?

**Comment by rocveralfre** [comment]
Hello, don't worry at the moment Visual Studio is not our main IDE, so we're not in hurry!

Anyway, I removed the extension version I had and installed latest (0.8.0), unfortunately I'm still experiencing the same issue (so no suggestions, no auto-completion etc.).

Using as dummy project the erlang_ls project itself, this is what I have currently in the path required from you:

```
[9:57] veralfre @ ~/Library/Logs/erlang_ls $ ls -lah ./erlang_ls/
total 0
drwxr-xr-x  2 veralfre  staff    64B 30 Gen 09:50 .
drwxr-xr-x  4 veralfre  staff   128B 30 Gen 09:50 ..
```

I'm not sure if this is some issue regarding permissions over the path I'm trying to use (still a subfolder of my home path) or something else..

As last attempt I can try to compile the language server (alone) and setup vim to check where the problem lies..

**Comment by rocveralfre** [comment]
In the end the real problem was missing crypto application due to a initial faulty installation of Erlang on my latop...

We can close this now! ✌️

**Comment by robertoaloi** [comment]
Glad that it works for you. Let us know if you find any other issue.
