### ISSUE TITLE
Customize debug/default mode

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/vscode#20]
The user should be able to select the verbosity of the server.

**Comment by benrs** [comment]
Just to clarify, you would like the user to be able to change the logging levels for this issue, right?

**Comment by robertoaloi** [comment]
Hi @benrs that is correct. See the ticket I linked in your PR (https://github.com/erlang-ls/erlang_ls/issues/430)

**Comment by jfacorro** [comment]
Fixed by #35
