### ISSUE TITLE
not work in Windows 10

### ISSUE THREAD

**Issue by erpcfe** [erlang-ls/vscode#21]
![image](https://user-images.githubusercontent.com/60412061/73372403-86f13c80-428d-11ea-95c3-2aa705f1eda4.png)

**Comment by robertoaloi** [comment]
Hi @erpcfe and thanks for the report. I suspect this is related to #8 .
I am preparing a branch which slightly change the invocation command, in a way which should be compatible with Windows systems.

**Comment by robertoaloi** [comment]
Fixed by #15
