### ISSUE TITLE
Method not implemented: $/setTraceNotification when changing Trace: Server

### ISSUE THREAD

**Issue by maxno-kivra** [erlang-ls/vscode#29]
The setting is changed, but I get this error in a popup, in the down right corner.

**Comment by robertoaloi** [comment]
Hi @maxno-kivra and thanks for reporting. This is due to VS Code sending a request which is not part of the protocol, so the message is a harmless warning. But I agree it's annoying, so I will get it fixed in the server. Related: https://github.com/Microsoft/vscode-languageserver-node/issues/170

**Comment by robertoaloi** [comment]
A fix for this is available in https://github.com/erlang-ls/erlang_ls/pull/449. Closing this in favour of https://github.com/erlang-ls/erlang_ls/issues/448. The fix will be available in the next release of the VS Code extension.

**Comment by maxno-kivra** [comment]
Lovely, thanks :)
