### ISSUE TITLE
Writing string with ':' character inside it crashes server

### ISSUE THREAD

**Issue by mazur-g** [erlang-ls/vscode#33]
When we put ':' character inside "", erlang_ls server crashes. It looks like vscode sends string without enclosing "". 
![Zrzut ekranu z 2020-02-29 18-37-37](https://user-images.githubusercontent.com/26421388/75612418-78fc3900-5b23-11ea-9e40-26f0c0c3c77f.png)
![Zrzut ekranu z 2020-02-29 18-37-59](https://user-images.githubusercontent.com/26421388/75612419-7994cf80-5b23-11ea-91a1-62703a0b8f2b.png)
![Zrzut ekranu z 2020-02-29 18-40-49](https://user-images.githubusercontent.com/26421388/75612420-7994cf80-5b23-11ea-9c05-5a79babf67e0.png)
![Zrzut ekranu z 2020-02-29 18-42-24](https://user-images.githubusercontent.com/26421388/75612421-7a2d6600-5b23-11ea-88d2-a1a8b4c6dc31.png)

**Comment by jfacorro** [comment]
Thank you for reporting this! This is a bug in Erlang LS, or at least something that we should be handling there. I will open an issue that references this one.

**Comment by jfacorro** [comment]
@mazur-g The bug is fixed in Erlang LS, it will be included in the next release for this extension.

**Comment by robertoaloi** [comment]
Fixed in `0.0.10`.
