### ISSUE TITLE
Elvis Enable\Disable

### ISSUE THREAD

**Issue by dubrovine** [erlang-ls/vscode#45]
Could you please add setting for disabling elvis code validation ?

**Comment by robertoaloi** [comment]
Hi @dubrovine and sorry for the late reply. Since version `0.0.12` (coming out today) it is possible to disable a specific type of diagnostics (e.g. `elvis`) via the `erlang_ls.config` file.

See https://erlang-ls.github.io/configuration/

**Comment by robertoaloi** [comment]
Solved since `0.0.12`
