### ISSUE TITLE
use escript to run els_dap

### ISSUE THREAD

**Issue by misaki214** [erlang-ls/vscode#85]
`els_dap` is not command in windows platform, use `escript` to execute `els_dap` script.

![Snipaste_2021-05-20_10-50-12](https://user-images.githubusercontent.com/81605435/118912159-edeea500-b959-11eb-8e69-b40df1129df0.png)

**Comment by TheGeorge** [comment]
Hi, thanks for flagging. Do you mind opening a PR with the fix?
