### ISSUE TITLE
Erlang keyword-brackets colorization issue since vscode 1.60

### ISSUE THREAD

**Issue by DOBRO** [erlang-ls/vscode#97]
After adding specific brackets (`if`-`end`, `case`-`end`, ...)
https://github.com/erlang-ls/vscode/blob/5ce656e95e8ab798a10df87f0b47275b07294e58/language-configuration.json#L9-L13
I ran into the issue regarding built-in bracket pair colorization. This is new feature since vscode 1.60 ( https://code.visualstudio.com/updates/v1_60#_high-performance-bracket-pair-colorization )

If this feature is enabled, all the `if`-`case`-`end` entries are highlighted with specific colors. See screenshot attached.

Now I don't know if my PR makes sense )))
https://github.com/erlang-ls/vscode/pull/96

<img width="883" alt="Снимок экрана 2021-09-24 в 18 39 08" src="https://user-images.githubusercontent.com/296845/134706091-f20ddb7f-7ba4-48c0-8ec2-064c1683add0.png">

**Comment by robertoaloi** [comment]
Hi @DOBRO and thanks for the report. I am not a VS Code user myself, so not sure how we should address this. The simplest solution would of course to stop including keywords as "brackets". Not sure if there's a better alternative. @TheGeorge @alanz ?

**Comment by robertoaloi** [comment]
Specifically, what I'm not sure about is if we are "abusing" the brackets settings by including keywords there or if there's an actual issue with the new solution upstream.

**Comment by DOBRO** [comment]
Here my position is: brackets are brackets and keywords are keywords. But someone might disagree with me.
In this case more flexible solution is to provide the option for choosing set of brackets, for example:
- brackets only;
- brackets + keywords.

**Comment by robertoaloi** [comment]
For now I'm going with the simplest solution, which is to only have actual brackets in the list. We can try and improve the situation as a follow up. Since I'm not a VS Code user myself, what's the major advantage of listing keywords within brackets?
